version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/AspNetCore.Scalar" # AspNetCore.Scalar.csproj
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 3
  - package-ecosystem: "npm"
    directory: "/src/AspNetCore.Scalar" # package.json
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 3
