name: Build & Test solution

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    name: Build & Test solution

    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --Configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal