name: Build & Test solution

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    name: Build & Test solution

    steps:
      - uses: actions/checkout@v4
        name: Checkout code
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            5.x
            6.x
            7.x
            8.x
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Run Test
        timeout-minutes: 15
        continue-on-error: false
        run: dotnet test -c Release --no-build --no-restore --verbosity normal