name: Build & Test solution

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    name: Build & Test solution

    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            5.x
            6.x
            7.x
            8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --framework net8.0 --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal