name: Publish to nuget.org

on: workflow_dispatch

jobs:
  build_and_test:

    name: Build and Test solution

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - uses: actions/upload-artifact@v2
        with:
          name: AspNetCore.Scalar
          path: artifact
        
  publish:

    name: Publish package

    runs-on: ubuntu-latest

    needs: build_and_test

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/download-artifact@v2
        with:
          name: AspNetCore.Scalar
          path: artifact

      - uses: nuget/setup-nuget@v1
        name: Setup NuGet
        with:
          nuget-version: '6.x'

      - name: Create the package
        run: dotnet pack --configuration Release --no-build --output . .
        
      - name: Publish the package
        run:  dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate