name: Publish to nuget.org

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: nuget/setup-nuget@v1
        name: Setup NuGet
        with:
          nuget-version: '6.x'

      - name: Create the package
        run: dotnet pack .\src\AspNetCore.Scalar\AspNetCore.Scalar.csproj -c Release
        
      - name: Publish the package
        run:  dotnet nuget push .\src\AspNetCore.Scalar\bin\Release\AspNetCore.Scalar.*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate