name: Publish to nuget.org

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    name: Publish nuget package

    steps:
      - uses: ./.github/workflows/build.yaml

      - uses: nuget/setup-nuget@v1
        name: Setup NuGet
        with:
          nuget-version: '6.x'

      - name: Create the package
        run: dotnet pack --configuration Release --no-build --output . .
        
      - name: Publish the package
        run:  dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate