name: Publish to Nuget.org

on: 
  workflow_dispatch:
      inputs:
        version:
          type: string
          required: true
          description: The version of the package
        pre-release:
          type: choice
          required: true
          default: 'true'
          options:
            - true
            - false
          description: Is this going to be a pre-release version? - On non-main branches this is always true

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      version_suffix: ${{ ( inputs.pre-release && github.ref != 'refs/heads/main' ) && '-rc' || '' }}

    name: Publish ${{ inputs.version }}${{ env.version_suffix }} nuget package

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            5.x
            6.x
            7.x
            8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        timeout-minutes: 15
        continue-on-error: false
        run: dotnet test -c Release --no-build --no-restore --verbosity normal --logger "trx;logfilename=results.trx" --results-directory ./test-results

      - name: Report Tests
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: .NET Test Report
          path: "${{ github.workspace }}/test-results/results.trx"
          reporter: dotnet-trx

      - uses: nuget/setup-nuget@v2
        name: Setup NuGet
        with:
          nuget-version: '6.x'

      - name: Create the package
        run: dotnet pack --configuration Release /p:Version=${{ inputs.version }}${{ env.version_suffix }} --no-build --output . .
        
      - name: Publish the package
        run:  dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate